apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "berg-operator.fullname" . }}
  labels:
    {{- include "berg-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "berg-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "berg-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "berg-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ include "berg-operator.imageTag" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: RUST_LOG
          value: {{ .Values.logLevel }}
        - name: CHALLENGE_NAMESPACE
          value: {{ .Values.config.challengeNamespace | quote }}
        - name: CHALLENGE_DOMAIN
          value: {{ .Values.config.challengeDomain | quote }}
        - name: CHALLENGE_HTTP_PORT
          value: {{ .Values.config.challengeHttpPort | quote }}
        - name: CHALLENGE_TLS_PORT
          value: {{ .Values.config.challengeTlsPort | quote }}
        - name: GATEWAY_NAME
          value: {{ .Values.config.gatewayName | quote }}
        - name: GATEWAY_NAMESPACE
          value: {{ .Values.config.gatewayNamespace | quote }}
        - name: CHALLENGE_HTTP_LISTENER_NAME
          value: {{ .Values.config.challengeHttpListenerName | quote }}
        - name: CHALLENGE_TLS_LISTENER_NAME
          value: {{ .Values.config.challengeTlsListenerName | quote }}
        - name: CHALLENGE_INSTANCE_TIMEOUT
          value: {{ .Values.config.defaultTimeout | quote }}
        - name: CHALLENGE_CPU_LIMIT
          value: {{ .Values.config.defaultCpuLimit | quote }}
        - name: CHALLENGE_CPU_REQUEST
          value: {{ .Values.config.defaultCpuRequest | quote }}
        - name: CHALLENGE_MEMORY_LIMIT
          value: {{ .Values.config.defaultMemoryLimit | quote }}
        - name: CHALLENGE_MEMORY_REQUEST
          value: {{ .Values.config.defaultMemoryRequest | quote }}
        - name: CHALLENGE_EGRESS_BANDWIDTH
          value: {{ .Values.config.defaultEgressBandwidth | quote }}
        - name: CHALLENGE_INGRESS_BANDWIDTH
          value: {{ .Values.config.defaultIngressBandwidth | quote }}
        - name: CHALLENGE_IMAGE_PULL_POLICY
          value: {{ .Values.config.imagePullPolicy | quote }}
        {{- if .Values.config.pullSecretName }}
        - name: PULL_SECRET_NAME
          value: {{ .Values.config.pullSecretName | quote }}
        {{- end }}
        {{- if .Values.config.defaultRuntimeClassName }}
        - name: CHALLENGE_RUNTIME_CLASS_NAME
          value: {{ .Values.config.defaultRuntimeClassName | quote }}
        {{- end }}
        - name: CHALLENGE_ADDITIONAL_HEADLESS_SERVICE
          value: {{ .Values.config.additionalHeadlessService | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
